---
taca_ngi_repo: https://github.com/NationalGenomicsInfrastructure/taca-ngi-pipeline.git
taca_ngi_dest: "{{ sw_path }}/taca-ngi-pipeline"
taca_ngi_version: 6715a4b4f26bd4a88fd2a04a04a2feb1937a9d76

flowcell_parser_repo: https://github.com/NationalGenomicsInfrastructure/flowcell_parser.git
flowcell_parser_dest: "{{ sw_path }}/flowcell_parser"
flowcell_parser_version: 0d0b8e781daf71d782b95201c4ec2d3c5ef02fb7

taca_repo: https://github.com/NationalGenomicsInfrastructure/TACA.git
taca_dest: "{{ sw_path }}/TACA"
taca_version: 9602239bb293892abd68f7fcf589b72148d40669

ngi_pipeline_analysisdir: "{{ ngi_pipeline_workdir }}/ANALYSIS"
ngi_pipeline_datadir: "{{ ngi_pipeline_workdir }}/DATA"
ngi_pipeline_deliverydir: "{{ ngi_pipeline_workdir }}/DELIVERY"
