multiqc_repo: https://github.com/MultiQC/MultiQC.git
multiqc_dest: "{{ sw_path }}/multiqc"
multiqc_version: "v1.25.2"

multiqc_ngi_repo: https://github.com/NationalGenomicsInfrastructure/MultiQC_NGI.git
multiqc_ngi_dest: "{{ sw_path }}/multiqc_ngi"
multiqc_ngi_version: "0.9.2"
