multiqc_repo: https://github.com/ewels/MultiQC.git
multiqc_dest: "{{ sw_path }}/multiqc"
multiqc_version: "v1.25.1"

multiqc_ngi_repo: https://github.com/NationalGenomicsInfrastructure/MultiQC_NGI.git
multiqc_ngi_dest: "{{ sw_path }}/multiqc_ngi"
multiqc_ngi_version: "0.8.2"
