---
sw_path: "{{ root_path }}/sw/"
ngi_containers: "/lupus/ngi/containers/"

anaconda_path: "{{ sw_path }}/anaconda"
ansible_path: "/lupus/ngi/irma3/ansible-env/"
default_env: "/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sw/uppmax/bin"
anaconda_env:
  PATH: "{{ anaconda_path }}/bin:{{ ansible_path }}/bin:{{ default_env }}" # this hopefully gets updated by anaconda role

#Nextflow defauts
nextflow_dest: "{{ sw_path }}/nextflow"

# Name of the script that should be sourced from the user to get the
# relevant environment variables setup. Perhaps move this to defaults vars.
bash_env_script: sourceme_common.sh
bash_env_upps_script: sourceme_upps.sh
bash_env_sthlm_script: sourceme_sthlm.sh

ngi_pipeline_repo: https://github.com/NationalGenomicsInfrastructure/ngi_pipeline.git
ngi_pipeline_dest: "{{ sw_path }}/ngi_pipeline"
ngi_pipeline_version: d1f206f2e28c6af498c711ff8b8d4a479d98440d
NGI_venv_name: "NGI"
NGI_venv_py3_name: "NGI_py3"
ngi_pipeline_venv: "{{ sw_path }}/anaconda/envs/{{ NGI_venv_name }}"

ngi_pipeline_conf: "{{ root_path }}/conf/"
ngi_resources: "{{ root_path }}/resources/"

ngi_pipeline_sthlm_delivery: ngi2016003
ngi_pipeline_upps_delivery: ngi2016001
ngi_sthlm_softlinks: "{{ proj_root }}/{{ ngi_pipeline_sthlm_delivery }}/nobackup/NGI/softlinks"
ngi_upps_softlinks: "{{ proj_root }}/{{ ngi_pipeline_upps_delivery }}/nobackup/NGI/softlinks"

ngi_pipeline_sthlm_path: "{{ proj_root }}/{{ ngi_pipeline_sthlm_delivery }}/private/"
ngi_pipeline_upps_path: "{{ proj_root }}/{{ ngi_pipeline_upps_delivery }}/private/"

ngi_pipeline_log_sthlm: "{{ ngi_pipeline_sthlm_path }}/log/ngi_pipeline.log"
ngi_pipeline_log_upps: "{{ ngi_pipeline_upps_path }}/log/ngi_pipeline.log"

ngi_pipeline_db_upps: "{{ ngi_pipeline_upps_path }}/db/records_db_upps.sql"
ngi_pipeline_db_sthlm: "{{ ngi_pipeline_sthlm_path }}/db/records_db_sthlm.sql"

piper_module_version: 1.5.1
gatk_bundle_b37: "/sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/"

sarek_tag: "2.7"
sarek_dest: "{{ sw_path }}/sarek"
sarek_containers: "{{ ngi_containers }}/sarek"

gatk_key: pontus.larsson_medsci.uu.se.key
snic_sthlm_creds: snic_credentials_sthlm.yaml
orderportal_creds: orderportal_credentials.yaml

recipient_mail_sthlm: ngi_pipeline_operators@scilifelab.se
recipient_mail_upps: medsci-molmed-bioinfo@googlegroups.com

validation_data_root: "/lupus/ngi/validation_data/"
validation_data:
 - "160915_ST-1234_0123_ATESTFCCXX"
 - "160915_ST-1234_0124_BCHR22CCXX"

# File with tools/software version in the deployed env
deployed_tool_versions: "{{ ngi_resources }}/deployed_tools.version"

# Empty placeholder that gets filled by tasks/pre-install.yml
root_path:
