---
ngi_reports_repo: https://github.com/NationalGenomicsInfrastructure/ngi_reports.git
ngi_reports_dest: "{{ sw_path }}/ngi_reports"
ngi_reports_version: 7d796861f3ebbf352f2073fcfa0129730dec83c6
ngi_reports_log: "{{ ngi_log_path }}/ngi_reports.log"

ngi_visual_repo: https://github.com/NationalGenomicsInfrastructure/ngi_visualizations.git
ngi_visual_dest: "{{ sw_path }}//ngi_visualization"
ngi_visual_version: bf1892faf5ebe16ad0979cfc83f9c72b90e2a5a0
