---
ngi_reports_repo: https://github.com/NationalGenomicsInfrastructure/ngi_reports.git
ngi_reports_dest: "{{ sw_path }}/ngi_reports"
ngi_reports_version: d3d20d8ebc02af38e2ecc9e805d1695fc89aa159
ngi_reports_log: "{{ ngi_log_path }}/ngi_reports.log"

ngi_mdx_outline_repo: https://github.com/NationalGenomicsInfrastructure/mdx_outline.git
ngi_mdx_outline_dest: "{{ sw_path }}//mdx_outline"
ngi_mdx_outline_version: f850211dca38b75873b7e60a23af24201426b58d
