- include: dependencies.yml

- name: Fetch TACA-ngi-pipeline from GitHub
  git: repo="{{ taca_ngi_repo }}"
       dest="{{ taca_ngi_dest }}"
       version="{{ taca_ngi_version }}"
       force=yes

- name: Install TACA-ngi-pipeline requirements
  pip:
    requirements: "{{ taca_ngi_dest }}/requirements.txt"
    virtualenv: "{{ ngi_pipeline_venv }}"

- name: Install TACA-ngi-pipeline
  pip:
    name: "file:{{ taca_ngi_dest }}"
    virtualenv: "{{ ngi_pipeline_venv }}"

- name: Create TACA delivery configs directory
  file: path="{{ ngi_pipeline_conf }}/TACA" state=directory mode=g+s

- name: Create TACA resources folders for each site
  file:
    path: "{{ ngi_resources }}/TACA/{{ item }}"
    state: directory
    mode: g+s
  with_items:
    - "upps"
    - "sthlm"

- set_fact:
    site: "upps"
    site_full: "uppsala"
    ngi_pipeline_site_path: "{{ ngi_pipeline_upps_path }}"
    ngi_site_softlinks: "{{ ngi_upps_softlinks }}"
    ngi_pipeline_site_delivery: "{{ ngi_pipeline_upps_delivery }}"
    recipient_mail: "{{ recipient_mail_upps }}"

- name: Deploy uppsala piper config
  template: src="site_taca_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{{ item.name }}_delivery.yml"
  with_items:
  - { proj_path: "{{ proj_root }}", name: "lupus" }
  - { proj_path: "{{ milou_delivery_root }}", name: "taca" }

- name: Deploy uppsala sarek config
  template: src="site_taca_sarek_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_taca_sarek_delivery.yml"

- set_fact:
    site: "sthlm"
    site_full: "stockholm"
    ngi_pipeline_site_path: "{{ ngi_pipeline_sthlm_path }}"
    ngi_site_softlinks: "{{ ngi_sthlm_softlinks }}"
    ngi_pipeline_site_delivery: "{{ ngi_pipeline_sthlm_delivery }}"
    recipient_mail: "{{ recipient_mail_sthlm }}"

- name: Deploy sthlm_taca_cleanup.yml config
  template: src="site_taca_cleanup.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_taca_cleanup.yml"

- name: Deploy sthlm_fastq_taca_delivery.yml config
  template: src="site_fastq_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{{ item.name }}_fastq_delivery.yml"
  with_items:
  - { proj_path: "{{ milou_delivery_root }}", name: "taca" }

- name: Deploy WGS standard stockholm configs
  template: src="site_taca_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{{ item.name }}_wgs_delivery.yml"
  with_items:
  - { proj_path: "{{ milou_delivery_root }}", name: "taca" }

- name: Deploy sthlm sarek config
  template: src="site_taca_sarek_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_taca_sarek_delivery.yml"

- name: Deploy application specific stockholm configs
  template: src="site_app_specific_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_taca_{{ item }}_delivery.yml"
  with_items: ['rna', 'denovo']

- name: Deploy runfolder delivery stockholm config
  template: src="site_taca_runfolder_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_taca_runfolder_delivery.yml"

- name: Deploy script for softlinking sthlm delivery Readmes
  template: src="create_delivery_readme_softlinks.sh.j2" dest="{{ ngi_resources }}/create_delivery_readme_softlinks.sh"

- name: Store taca tools version on deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "{{ item.tool_name }}: {{ item.tool_version }}"
  with_items:
    - { tool_name: "TACA", tool_version: "{{ taca_version }}" }
    - { tool_name: "taca-ngi-pipeline", tool_version: "{{ taca_ngi_version }}" }
    - { tool_name: "StatusDB", tool_version: "{{ statusdb_version }}" }
    - { tool_name: "flowcell_parser", tool_version: "{{ flowcell_parser_version }}" }
